// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.7.1
// source: video.proto

package video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoClient interface {
	GetVideoByVideoId(ctx context.Context, in *VideoIdReq, opts ...grpc.CallOption) (*VideoInfoReply, error)
	GetVideoNumByAuthorId(ctx context.Context, in *AuthorIdReq, opts ...grpc.CallOption) (*VideoNumReply, error)
}

type videoClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoClient(cc grpc.ClientConnInterface) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) GetVideoByVideoId(ctx context.Context, in *VideoIdReq, opts ...grpc.CallOption) (*VideoInfoReply, error) {
	out := new(VideoInfoReply)
	err := c.cc.Invoke(ctx, "/video.video/getVideoByVideoId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetVideoNumByAuthorId(ctx context.Context, in *AuthorIdReq, opts ...grpc.CallOption) (*VideoNumReply, error) {
	out := new(VideoNumReply)
	err := c.cc.Invoke(ctx, "/video.video/getVideoNumByAuthorId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
// All implementations must embed UnimplementedVideoServer
// for forward compatibility
type VideoServer interface {
	GetVideoByVideoId(context.Context, *VideoIdReq) (*VideoInfoReply, error)
	GetVideoNumByAuthorId(context.Context, *AuthorIdReq) (*VideoNumReply, error)
	mustEmbedUnimplementedVideoServer()
}

// UnimplementedVideoServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServer struct {
}

func (UnimplementedVideoServer) GetVideoByVideoId(context.Context, *VideoIdReq) (*VideoInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoByVideoId not implemented")
}
func (UnimplementedVideoServer) GetVideoNumByAuthorId(context.Context, *AuthorIdReq) (*VideoNumReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoNumByAuthorId not implemented")
}
func (UnimplementedVideoServer) mustEmbedUnimplementedVideoServer() {}

// UnsafeVideoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServer will
// result in compilation errors.
type UnsafeVideoServer interface {
	mustEmbedUnimplementedVideoServer()
}

func RegisterVideoServer(s grpc.ServiceRegistrar, srv VideoServer) {
	s.RegisterService(&Video_ServiceDesc, srv)
}

func _Video_GetVideoByVideoId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideoByVideoId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/getVideoByVideoId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideoByVideoId(ctx, req.(*VideoIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetVideoNumByAuthorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideoNumByAuthorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/getVideoNumByAuthorId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideoNumByAuthorId(ctx, req.(*AuthorIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Video_ServiceDesc is the grpc.ServiceDesc for Video service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Video_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getVideoByVideoId",
			Handler:    _Video_GetVideoByVideoId_Handler,
		},
		{
			MethodName: "getVideoNumByAuthorId",
			Handler:    _Video_GetVideoNumByAuthorId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
