// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"

	"github.com/ev1lQuark/tiktok/service/like/rpc/internal/logic"
	"github.com/ev1lQuark/tiktok/service/like/rpc/internal/svc"
	"github.com/ev1lQuark/tiktok/service/like/rpc/types/like"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	like.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

// 根据userId获取本账号所发视频获赞总数
func (s *LikeServer) GetTotalFavoriteNum(ctx context.Context, in *like.GetTotalFavoriteNumReq) (*like.GetTotalFavoriteNumReply, error) {
	l := logic.NewGetTotalFavoriteNumLogic(ctx, s.svcCtx)
	return l.GetTotalFavoriteNum(in)
}

// 根据userId获取本账号喜欢（点赞）总数
func (s *LikeServer) GetFavoriteCountByUserId(ctx context.Context, in *like.GetFavoriteCountByUserIdReq) (*like.GetFavoriteCountByUserIdReply, error) {
	l := logic.NewGetFavoriteCountByUserIdLogic(ctx, s.svcCtx)
	return l.GetFavoriteCountByUserId(in)
}

// 根据videoId获取视屏点赞总数
func (s *LikeServer) GetFavoriteCountByVideoId(ctx context.Context, in *like.GetFavoriteCountByVideoIdReq) (*like.GetFavoriteCountByVideoIdReply, error) {
	l := logic.NewGetFavoriteCountByVideoIdLogic(ctx, s.svcCtx)
	return l.GetFavoriteCountByVideoId(in)
}

// 根据userId和videoId判断是否点赞
func (s *LikeServer) IsFavorite(ctx context.Context, in *like.IsFavoriteReq) (*like.IsFavoriteReply, error) {
	l := logic.NewIsFavoriteLogic(ctx, s.svcCtx)
	return l.IsFavorite(in)
}
