// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: like.proto

package like

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LikeClient is the client API for Like service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikeClient interface {
	// 根据userId获取本账号所发视频获赞总数
	GetFavoriteCountByAuthorIds(ctx context.Context, in *GetFavoriteCountByAuthorIdsReq, opts ...grpc.CallOption) (*GetFavoriteCountByAuthorIdsReply, error)
	// 根据userId获取本账号喜欢（点赞）总数
	GetFavoriteCountByUserIds(ctx context.Context, in *GetFavoriteCountByUserIdsReq, opts ...grpc.CallOption) (*GetFavoriteCountByUserIdsReply, error)
	// 根据videoId获取视频点赞总数
	GetFavoriteCountByVideoIds(ctx context.Context, in *GetFavoriteCountByVideoIdsReq, opts ...grpc.CallOption) (*GetFavoriteCountByVideoIdsReply, error)
	// 根据userId和videoId判断是否点赞
	IsFavorite(ctx context.Context, in *IsFavoriteReq, opts ...grpc.CallOption) (*IsFavoriteReply, error)
}

type likeClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeClient(cc grpc.ClientConnInterface) LikeClient {
	return &likeClient{cc}
}

func (c *likeClient) GetFavoriteCountByAuthorIds(ctx context.Context, in *GetFavoriteCountByAuthorIdsReq, opts ...grpc.CallOption) (*GetFavoriteCountByAuthorIdsReply, error) {
	out := new(GetFavoriteCountByAuthorIdsReply)
	err := c.cc.Invoke(ctx, "/user.like/getFavoriteCountByAuthorIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) GetFavoriteCountByUserIds(ctx context.Context, in *GetFavoriteCountByUserIdsReq, opts ...grpc.CallOption) (*GetFavoriteCountByUserIdsReply, error) {
	out := new(GetFavoriteCountByUserIdsReply)
	err := c.cc.Invoke(ctx, "/user.like/getFavoriteCountByUserIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) GetFavoriteCountByVideoIds(ctx context.Context, in *GetFavoriteCountByVideoIdsReq, opts ...grpc.CallOption) (*GetFavoriteCountByVideoIdsReply, error) {
	out := new(GetFavoriteCountByVideoIdsReply)
	err := c.cc.Invoke(ctx, "/user.like/getFavoriteCountByVideoIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) IsFavorite(ctx context.Context, in *IsFavoriteReq, opts ...grpc.CallOption) (*IsFavoriteReply, error) {
	out := new(IsFavoriteReply)
	err := c.cc.Invoke(ctx, "/user.like/isFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeServer is the server API for Like service.
// All implementations must embed UnimplementedLikeServer
// for forward compatibility
type LikeServer interface {
	// 根据userId获取本账号所发视频获赞总数
	GetFavoriteCountByAuthorIds(context.Context, *GetFavoriteCountByAuthorIdsReq) (*GetFavoriteCountByAuthorIdsReply, error)
	// 根据userId获取本账号喜欢（点赞）总数
	GetFavoriteCountByUserIds(context.Context, *GetFavoriteCountByUserIdsReq) (*GetFavoriteCountByUserIdsReply, error)
	// 根据videoId获取视频点赞总数
	GetFavoriteCountByVideoIds(context.Context, *GetFavoriteCountByVideoIdsReq) (*GetFavoriteCountByVideoIdsReply, error)
	// 根据userId和videoId判断是否点赞
	IsFavorite(context.Context, *IsFavoriteReq) (*IsFavoriteReply, error)
	mustEmbedUnimplementedLikeServer()
}

// UnimplementedLikeServer must be embedded to have forward compatible implementations.
type UnimplementedLikeServer struct {
}

func (UnimplementedLikeServer) GetFavoriteCountByAuthorIds(context.Context, *GetFavoriteCountByAuthorIdsReq) (*GetFavoriteCountByAuthorIdsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFavoriteCountByAuthorIds not implemented")
}
func (UnimplementedLikeServer) GetFavoriteCountByUserIds(context.Context, *GetFavoriteCountByUserIdsReq) (*GetFavoriteCountByUserIdsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFavoriteCountByUserIds not implemented")
}
func (UnimplementedLikeServer) GetFavoriteCountByVideoIds(context.Context, *GetFavoriteCountByVideoIdsReq) (*GetFavoriteCountByVideoIdsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFavoriteCountByVideoIds not implemented")
}
func (UnimplementedLikeServer) IsFavorite(context.Context, *IsFavoriteReq) (*IsFavoriteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFavorite not implemented")
}
func (UnimplementedLikeServer) mustEmbedUnimplementedLikeServer() {}

// UnsafeLikeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeServer will
// result in compilation errors.
type UnsafeLikeServer interface {
	mustEmbedUnimplementedLikeServer()
}

func RegisterLikeServer(s grpc.ServiceRegistrar, srv LikeServer) {
	s.RegisterService(&Like_ServiceDesc, srv)
}

func _Like_GetFavoriteCountByAuthorIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteCountByAuthorIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).GetFavoriteCountByAuthorIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.like/getFavoriteCountByAuthorIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).GetFavoriteCountByAuthorIds(ctx, req.(*GetFavoriteCountByAuthorIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_GetFavoriteCountByUserIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteCountByUserIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).GetFavoriteCountByUserIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.like/getFavoriteCountByUserIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).GetFavoriteCountByUserIds(ctx, req.(*GetFavoriteCountByUserIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_GetFavoriteCountByVideoIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteCountByVideoIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).GetFavoriteCountByVideoIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.like/getFavoriteCountByVideoIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).GetFavoriteCountByVideoIds(ctx, req.(*GetFavoriteCountByVideoIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_IsFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).IsFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.like/isFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).IsFavorite(ctx, req.(*IsFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Like_ServiceDesc is the grpc.ServiceDesc for Like service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Like_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.like",
	HandlerType: (*LikeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getFavoriteCountByAuthorIds",
			Handler:    _Like_GetFavoriteCountByAuthorIds_Handler,
		},
		{
			MethodName: "getFavoriteCountByUserIds",
			Handler:    _Like_GetFavoriteCountByUserIds_Handler,
		},
		{
			MethodName: "getFavoriteCountByVideoIds",
			Handler:    _Like_GetFavoriteCountByVideoIds_Handler,
		},
		{
			MethodName: "isFavorite",
			Handler:    _Like_IsFavorite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "like.proto",
}
