// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package like

import (
	"context"

	"github.com/ev1lQuark/tiktok/service/comment/rpc/types/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFavoriteCountByVideoIdReply = comment.GetFavoriteCountByVideoIdReply
	GetFavoriteCountByVideoIdReq   = comment.GetFavoriteCountByVideoIdReq

	Like interface {
		// 根据videoId获取视屏评论总数
		GetCommentCountByVideoId(ctx context.Context, in *GetFavoriteCountByVideoIdReq, opts ...grpc.CallOption) (*GetFavoriteCountByVideoIdReply, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

// 根据videoId获取视屏评论总数
func (m *defaultLike) GetCommentCountByVideoId(ctx context.Context, in *GetFavoriteCountByVideoIdReq, opts ...grpc.CallOption) (*GetFavoriteCountByVideoIdReply, error) {
	client := comment.NewLikeClient(m.cli.Conn())
	return client.GetCommentCountByVideoId(ctx, in, opts...)
}
