// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AuthorID    int64     `gorm:"column:author_id;not null" json:"author_id"`
	PlayURL     string    `gorm:"column:play_url;not null" json:"play_url"`
	CoverURL    string    `gorm:"column:cover_url;not null" json:"cover_url"`
	PublishTime time.Time `gorm:"column:publish_time;not null" json:"publish_time"`
	Title       string    `gorm:"column:title;not null" json:"title"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
