// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/ev1lQuark/tiktok/service/user/rpc/internal/logic"
	"github.com/ev1lQuark/tiktok/service/user/rpc/internal/svc"
	"github.com/ev1lQuark/tiktok/service/user/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetNames(ctx context.Context, in *user.IdListReq) (*user.NameListReply, error) {
	l := logic.NewGetNamesLogic(ctx, s.svcCtx)
	return l.GetNames(in)
}
