// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package commentclient

import (
	"context"

	"github.com/ev1lQuark/tiktok/service/comment/rpc/types/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetComentCountByVideoIdReply = comment.GetComentCountByVideoIdReply
	GetComentCountByVideoIdReq   = comment.GetComentCountByVideoIdReq

	Comment interface {
		// 根据videoId获取视屏评论总数
		GetCommentCountByVideoId(ctx context.Context, in *GetComentCountByVideoIdReq, opts ...grpc.CallOption) (*GetComentCountByVideoIdReply, error)
	}

	defaultComment struct {
		cli zrpc.Client
	}
)

func NewComment(cli zrpc.Client) Comment {
	return &defaultComment{
		cli: cli,
	}
}

// 根据videoId获取视屏评论总数
func (m *defaultComment) GetCommentCountByVideoId(ctx context.Context, in *GetComentCountByVideoIdReq, opts ...grpc.CallOption) (*GetComentCountByVideoIdReply, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.GetCommentCountByVideoId(ctx, in, opts...)
}
