// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"github.com/ev1lQuark/tiktok/service/comment/rpc/internal/logic"
	"github.com/ev1lQuark/tiktok/service/comment/rpc/internal/svc"
	"github.com/ev1lQuark/tiktok/service/comment/rpc/types/comment"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

// 根据videoId获取视屏评论总数
func (s *CommentServer) GetCommentCountByVideoId(ctx context.Context, in *comment.GetComentCountByVideoIdReq) (*comment.GetComentCountByVideoIdReply, error) {
	l := logic.NewGetCommentCountByVideoIdLogic(ctx, s.svcCtx)
	return l.GetCommentCountByVideoId(in)
}
