// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"github.com/ev1lQuark/tiktok/service/comment/rpc/internal/logic"
	"github.com/ev1lQuark/tiktok/service/comment/rpc/internal/svc"
	"github.com/ev1lQuark/tiktok/service/comment/rpc/types/comment"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

// 根据videoId获取视屏评论总数
func (s *LikeServer) GetCommentCountByVideoId(ctx context.Context, in *comment.GetFavoriteCountByVideoIdReq) (*comment.GetFavoriteCountByVideoIdReply, error) {
	l := logic.NewGetCommentCountByVideoIdLogic(ctx, s.svcCtx)
	return l.GetCommentCountByVideoId(in)
}
