// Code generated by goctl. DO NOT EDIT.
package types

type LikeRequest struct {
	Token      string `form:"token":"token"`
	VideoId    string `form:"video_id"`
	ActionType string `form:"action_type"`
}

type LikeResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
}

type LikeListRequest struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type LikeListResponse struct {
	StatusCode string      `json:"status_code"`
	StatusMsg  string      `json:"status_msg"`
	VideoList  []VideoList `json:"video_list"`
}

type VideoList struct {
	ID            int64  `json:"id"`
	Author        Author `json:"author"`
	PlayURL       string `json:"play_url"`
	CoverURL      string `json:"cover_url"`
	FavoriteCount int64  `json:"favorite_count"`
	CommentCount  int64  `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}

type Author struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	FollowCount     int64  `json:"follow_count"`
	FollowerCount   int64  `json:"follower_count"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  string `json:"total_favorited"`
	WorkCount       int64  `json:"work_count"`
	FavoriteCount   int64  `json:"favorite_count"`
}
