// Code generated by goctl. DO NOT EDIT.
package types

type GetCommentRequest struct {
	Token       string `form:"token":"token"`
	VideoId     string `form:"video_id"`
	ActionType  string `form:"action_type"`
	CommentText string `form:"comment_text"`
	CommentId   string `form:"comment_id,optional"`
}

type GetCommentResponse struct {
	StatusCode int64   `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
	Comment    Comment `json:"comment"`
}

type Comment struct {
	ID         int64  `json:"id"`
	User       User   `json:"user"`
	Content    string `json:"content"`
	CreateDate string `json:"create_date"`
}

type GetCommentListRequest struct {
	Token   string `form:"token"`
	VideoId string `form:"video_id"`
}

type GetCommentListResponse struct {
	StatusCode  int64         `json:"status_code"`
	StatusMsg   string        `json:"status_msg"`
	CommentList []CommentList `json:"comment_list"`
}

type CommentList struct {
	ID         int64  `json:"id"`
	User       User   `json:"user"`
	Content    string `json:"content"`
	CreateDate string `json:"create_date"`
}

type User struct {
	ID              int    `json:"id"`
	Name            string `json:"name"`
	FollowCount     int    `json:"follow_count"`
	FollowerCount   int    `json:"follower_count"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  string `json:"total_favorited"`
	WorkCount       int    `json:"work_count"`
	FavoriteCount   int    `json:"favorite_count"`
}
