// Code generated by goctl. DO NOT EDIT.
package types

type GetCommentRequest struct {
	Token       string `json:"token"`
	VideoId     string `json:"video_id"`
	ActionType  string `json:"action_type"`
	CommentText string `json:"comment_text"`
	CommentId   string `json:"comment_id"`
}

type GetCommentResponse struct {
	StatusCode int64   `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
	Comment    Comment `json:"comment"`
}

type Comment struct {
	ID         int64  `json:"id"`
	User       User   `json:"user"`
	Content    string `json:"content"`
	CreateDate string `json:"create_date"`
}

type GetCommentListRequest struct {
	Token   string `json:"token"`
	VideoId string `json:"video_id"`
}

type GetCommentListResponse struct {
	StatusCode  int64         `json:"status_code"`
	StatusMsg   string        `json:"status_msg"`
	CommentList []CommentList `json:"comment_list"`
}

type CommentList struct {
	ID         int64  `json:"id"`
	User       User   `json:"user"`
	Content    string `json:"content"`
	CreateDate string `json:"create_date"`
}

type User struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}
