// Code generated by goctl. DO NOT EDIT.
package types

type LoginOrRegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginOrRegisterReply struct {
	Code    int32  `json:"status_code"`
	Message string `json:"status_message"`
	UserId  int64  `json:"user_id"`
	Token   string `json:"token"`
}

type UserInfoReq struct {
	UserId string `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfoReply struct {
	Code    int32  `json:"status_code"`
	Message string `json:"status_message"`
	User    *User  `json:"user"`
}

type User struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}
