// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/ev1lQuark/tiktok/service/like/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/favorite/action",
				Handler: likeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/favorite/list",
				Handler: getLikeListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin"),
	)
}
